{% set name = "reportseff" %}
{% set version = "2.10.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/reportseff-{{ version }}.tar.gz
  sha256: 03e4f5607533cb14e413c2161b004dfcbb079fe58c8167872cc32ae258af7471

build:
  entry_points:
    - reportseff = reportseff.console:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - uv_build >=0.9.25,<0.10.0
    - pip
  run:
    - python >={{ python_min }}
    - click >=6.7

test:
  imports:
    - reportseff
  commands:
    - pip check
    - reportseff --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/troycomi/reportseff
  summary: Tablular seff output
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jdblischak
    - troycomi
