{% set name = "reportseff" %}
{% set version = "2.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/reportseff-{{ version }}.tar.gz
  sha256: 1f5d193883569bf9b89c7fe41f1f95714b815258bbed172c073bf62b502e4fcf

build:
  entry_points:
    - reportseff = reportseff.console:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=1.0.0
    - pip
  run:
    - python >={{ python_min }}
    - click >=6.7
    - importlib-metadata >=4.8.2

test:
  imports:
    - reportseff
  commands:
    - pip check
    - reportseff --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/troycomi/reportseff
  summary: Tablular seff output
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jdblischak
    - troycomi
