{% set name = "reportseff" %}
{% set version = "2.7.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/reportseff-{{ version }}.tar.gz
  sha256: 6d664ca627a7d2bb6451ddf2ea106dde202ff043653123d8be5d539b1af9393c

build:
  entry_points:
    - reportseff = reportseff.console:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.7
    - click >=6.7
    - importlib-metadata >=4.8.2

test:
  imports:
    - reportseff
  commands:
    - pip check
    - reportseff --help
  requires:
    - pip

about:
  home: https://github.com/troycomi/reportseff
  summary: Tablular seff output
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jdblischak
    - troycomi
