{% set name = "reportseff" %}
{% set version = "2.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/reportseff-{{ version }}.tar.gz
  sha256: 62a0d79ac0d883c365cf509058c0a45bf6c97dc5789ed4ed09cc250ae4c72806

build:
  entry_points:
    - reportseff = reportseff.console:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.8
    - click >=6.7
    - importlib-metadata >=4.8.2

test:
  imports:
    - reportseff
  commands:
    - pip check
    - reportseff --help
  requires:
    - pip

about:
  home: https://github.com/troycomi/reportseff
  summary: Tablular seff output
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jdblischak
    - troycomi
